openapi: 3.0.3

info:
  title: Resource Service API
  description: API description.
  version: 1.0.0
paths: { }
components:
  schemas:

    IdDto:
      type: object
      properties:
        id:
          type: integer
    MetadataDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        artist:
          type: string
        album:
          type: string
        duration:
          type: string
        year:
          type: integer


