server:
  port: 8072
  servlet:
    context-path: /api

spring:
   application:
     name: song-service
   datasource:
     username: postgres
     password: rdm
     url: jdbc:postgresql://192.168.1.241:5433/song
     driver-class-name: org.postgresql.Driver

