server:
  port: 8071
  servlet:
    context-path: /api

spring:
   application:
     name: resource-service
   datasource:
     username: postgres
     password: rdm
     url: jdbc:postgresql://192.168.1.241:5434/resource
     driver-class-name: org.postgresql.Driver
   servlet:
     multipart:
       max-file-size: 10MB
       max-request-size: 10MB
